cc_test(
  name = "eeprom-wifi-test",
  srcs = ["eeprom-wifi-test.cpp"],
  deps = [
    "//:eeprom-wifi",
    "//test/mock:EEPROM",
    "//test/mock:ESP8266WiFi",
    "@gmock-global//:gmock-global",
    "@gtest//:gtest",
    "@gtest//:gtest_main",
  ],
)
